// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6OUY00wuQ1vSCUqCFWhT-8pEAU8pHjk',
    appId: '1:183709247181:web:2813a509c0dc4ab694ab84',
    messagingSenderId: '183709247181',
    projectId: 'golearnlishflutter',
    authDomain: 'golearnlishflutter.firebaseapp.com',
    storageBucket: 'golearnlishflutter.appspot.com',
    measurementId: 'G-9EK4MG26P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-8A3mf2gAJAznCO2IJCxGntxcb8ngbHI',
    appId: '1:183709247181:android:ac1bf18de4ecf89394ab84',
    messagingSenderId: '183709247181',
    projectId: 'golearnlishflutter',
    storageBucket: 'golearnlishflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8HNxR8wnv7D-QU-wd7Av8gs9HMn2Rds',
    appId: '1:183709247181:ios:cd85f0c3cdfa57d994ab84',
    messagingSenderId: '183709247181',
    projectId: 'golearnlishflutter',
    storageBucket: 'golearnlishflutter.appspot.com',
    iosBundleId: 'com.example.golearnlish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8HNxR8wnv7D-QU-wd7Av8gs9HMn2Rds',
    appId: '1:183709247181:ios:cd85f0c3cdfa57d994ab84',
    messagingSenderId: '183709247181',
    projectId: 'golearnlishflutter',
    storageBucket: 'golearnlishflutter.appspot.com',
    iosBundleId: 'com.example.golearnlish',
  );
}
